# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QtVtg9nYeYnbxbT5SqcqCelEx1BofqRb
"""

# 1 - Mount Drive and set paths
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

BASE_DIR = "/content/drive/MyDrive/Colab Notebooks/Project 3 Data/Project 3 Data"   # <--- update this if your folder is elsewhere
!ls -la "{BASE_DIR}"

!pip install ultralytics
!pip install ultralytics opencv-python


# This Project includes Two Major Sections
# (1) Image Processing and (2) Componet Detection


#First Section: Using OpenCV to mask out an image of a motherboard
#Second Section: Using YOLOv11 to classify componets from a PCB

# Note: The project tasks can be handled by packages like OpenCV, Ultralytics, PyTorch, Numpy, and Pillow.

#OpenCV will be harnessed in the intial phase for precise image masking, esuring the extraction of relevant features
# from the motherboard image. Subsequently, YOLO will be emplyed to conduct componet classfication on PCB

# Step 1: Object Masking: Used for machines to identify and isolate specfici objects within images from the background.

import cv2 #Use OpenCV tools to read the image
import numpy as np
from google.colab.patches import cv2_imshow

image_path = f"{BASE_DIR}/motherboard_image.JPEG"

image = cv2.imread(image_path)


gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2_imshow(gray)

# Apply the binary thresholding

ret, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY+ cv2.THRESH_OTSU)
cv2_imshow( thresh)
# 127 is a threshold value vs the 255, white colour. It suggests what colour each pixel will be.

edges = cv2.Canny(gray, 50, 150)
cv2_imshow(edges)

contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
contours_image = image.copy()
cv2.drawContours(image, contours, -1, (0, 255, 0), 3)
cv2_imshow(image)



from ultralytics import YOLO

#Step 2: YOLOv11 Training

# Train a model

model = YOLO("yolo11n.pt") # Load the pretrained model


data = f"{BASE_DIR}/data/data/data.yaml"

Results = model.train(data = data,
                    epochs = 120,
                     imgsz = 900,
                      batch= 8,
                      name='pcb_yolo_model'
)

EVAL_DIR = "/content/drive/MyDrive/Colab Notebooks/Project 3 Data/Project 3 Data/data/data/evaluation/"

model.predict(
    source=EVAL_DIR,
    save=True,
    imgsz=1200,
    line_width=5
)



!cp -r /content/runs/detect/predict /content/drive/MyDrive/